# Local Development Dependencies
services:
  postgres:
    # https://github.com/postgis/docker-postgis
    image: postgis/postgis:17-3.5
    platform: linux/amd64
    restart: unless-stopped
    environment:
      POSTGRES_DB: local_discovercare
      POSTGRES_USER: discovercare
      POSTGRES_PASSWORD: discovercare
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: ./.postgresql/data
        target: /var/lib/postgresql/data # changes in postgres v18+
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
